version: '3.5'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /mysqldata:/var/lib/mysql
